apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-storefront-bff
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Phuc-215/yas.git
    targetRevision: HEAD
    path: k8s/charts/storefront-bff
    helm:
      valueFiles:
        - ../../overlays/dev/storefront-bff.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true        # xóa resource không còn trong Git
      selfHeal: true     # tự rollback nếu ai sửa tay trên cluster
    syncOptions:
      - CreateNamespace=true