apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-webhook
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/miserybee99/devops-project.git
      targetRevision: feature/gitops
      path: k8s/charts/webhook
      helm:
        valueFiles:
          - $values/overlays/staging/webhook.yaml
    - repoURL: https://github.com/Phuc-215/yas-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy: {}
