apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-yas-reloader
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/miserybee99/devops-project.git
      targetRevision: main
      path: k8s/charts/yas-configuration
      helm:
        valueFiles:
          - $values/overlays/staging/yas-configuration.yaml
    - repoURL: https://github.com/Phuc-215/yas-deploy.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
